from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def read_rules(path: Path) -> dict[str, Any]:
    with path.open() as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError("candidate rules JSON must be an object")
    return payload


def top_candidate(payload: dict[str, Any]) -> dict[str, Any] | None:
    candidates = payload.get("candidates", [])
    if not isinstance(candidates, list) or not candidates:
        return None
    first = candidates[0]
    if not isinstance(first, dict):
        return None
    return first


def strategy_rules_payload(source: Path, candidate: dict[str, Any] | None) -> dict[str, Any]:
    warnings = [
        "Research scaffold only. Do not use for live trading.",
        "Candidate rules are one-feature ENTRY-vs-SKIP thresholds, not a complete strategy.",
        "Feature-to-Pine expression mapping must be reviewed before TradingView testing.",
    ]
    return {
        "version": "strategy_rules.v1",
        "generatedAt": datetime.now(UTC).isoformat(),
        "status": "research_scaffold",
        "source": str(source),
        "topRule": candidate,
        "warnings": warnings,
    }


def pine_expression(feature: str) -> tuple[str, list[str]]:
    comments: list[str] = []
    mapping = {
        "feature_close": ("close", []),
        "feature_close_above_ema25": ("close > ta.ema(close, 25)", []),
        "feature_close_above_sma100": ("close > ta.sma(close, 100)", []),
        "feature_distance_to_ema25_pct": (
            "((close - ta.ema(close, 25)) / ta.ema(close, 25)) * 100",
            [],
        ),
        "feature_distance_to_sma100_pct": (
            "((close - ta.sma(close, 100)) / ta.sma(close, 100)) * 100",
            [],
        ),
        "feature_recent_5_return_pct": ("((close - close[5]) / close[5]) * 100", []),
        "feature_recent_10_return_pct": ("((close - close[10]) / close[10]) * 100", []),
        "feature_recent_20_return_pct": ("((close - close[20]) / close[20]) * 100", []),
        "feature_recent_20_high": ("ta.highest(high, 20)", []),
        "feature_recent_20_low": ("ta.lowest(low, 20)", []),
        "feature_close_rank_recent_20": (
            "((close - ta.lowest(low, 20)) / math.max(ta.highest(high, 20) - ta.lowest(low, 20), syminfo.mintick))",
            [],
        ),
    }
    if feature in mapping:
        return mapping[feature]
    comments.append(f"TODO: map EdgeLord export feature `{feature}` to a Pine expression.")
    return ("na", comments)


def numeric_literal(value: Any) -> str:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "na"
    return f"{numeric:.10g}"


def comparison_operator(direction: Any) -> str:
    return ">=" if direction == ">=" else "<="


def pine_stub(candidate: dict[str, Any] | None) -> str:
    lines = [
        "//@version=5",
        'strategy("EdgeLord SOXL/SOXS Candidate Scaffold", overlay=true, pyramiding=0)',
        "",
        "// Generated by EdgeLord research tooling.",
        "// Research scaffold only. Validate the rule, feature mapping, and symbol behavior before TradingView use.",
        "// This is not a live-trading strategy.",
        "",
    ]

    if not candidate:
        lines.extend([
            "// No candidate rule is available yet.",
            "// Add replay-safe ENTRY and SKIP labels, then rerun `pnpm research:report`.",
            "candidateSignal = false",
        ])
    else:
        feature = str(candidate.get("feature", ""))
        direction = comparison_operator(candidate.get("direction"))
        threshold = numeric_literal(candidate.get("threshold"))
        expression, comments = pine_expression(feature)
        lines.extend([
            f"// Top candidate: {feature} {direction} {threshold}",
            f"// precision={float(candidate.get('precision', 0)):.4f} recall={float(candidate.get('recall', 0)):.4f} lift={float(candidate.get('lift', 0)):.4f}",
        ])
        lines.extend(f"// {comment}" for comment in comments)
        lines.extend([
            f"candidateFeature = {expression}",
            f"candidateSignal = not na(candidateFeature) and candidateFeature {direction} {threshold}",
        ])

    lines.extend([
        "",
        'plotshape(candidateSignal, title="Candidate ENTRY", style=shape.triangleup, location=location.belowbar, size=size.tiny)',
        'if candidateSignal and strategy.position_size == 0',
        '    strategy.entry("Candidate Long", strategy.long)',
        "",
        "// Exits are intentionally not generated yet.",
        "// EdgeLord needs tested exit rules or explicit exported exit logic before this becomes a complete strategy.",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate EdgeLord strategy-rules JSON and a Pine Script scaffold.")
    parser.add_argument("--rules-json", required=True, type=Path, help="Path to candidate-rules.json")
    parser.add_argument("--rules-output", required=True, type=Path, help="Path to write strategy_rules.v1.json")
    parser.add_argument("--pine-output", required=True, type=Path, help="Path to write strategy_soxl_soxs.pine")
    args = parser.parse_args()

    candidate_rules = read_rules(args.rules_json)
    candidate = top_candidate(candidate_rules)

    args.rules_output.parent.mkdir(parents=True, exist_ok=True)
    args.rules_output.write_text(f"{json.dumps(strategy_rules_payload(args.rules_json, candidate), indent=2)}\n")

    args.pine_output.parent.mkdir(parents=True, exist_ok=True)
    args.pine_output.write_text(pine_stub(candidate))


if __name__ == "__main__":
    main()
