from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def read_rules(path: Path) -> dict[str, Any]:
    with path.open() as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError("candidate rules JSON must be an object")
    return payload


def top_candidate(payload: dict[str, Any]) -> dict[str, Any] | None:
    candidates = payload.get("candidates", [])
    if not isinstance(candidates, list) or not candidates:
        return None
    first = candidates[0]
    if not isinstance(first, dict):
        return None
    return first


def strategy_rules_payload(
    human_source: Path,
    human_candidate: dict[str, Any] | None,
    return_source: Path | None,
    return_candidate: dict[str, Any] | None,
) -> dict[str, Any]:
    warnings = [
        "Research scaffold only. Do not use for live trading.",
        "Human-mimic rules are one-feature ENTRY-vs-SKIP thresholds, not a complete strategy.",
        "Return-optimized rules are closed-label filters, not full-history backtests.",
        "Feature-to-Pine expression mapping must be reviewed before TradingView testing.",
    ]
    return {
        "version": "strategy_rules.v1",
        "generatedAt": datetime.now(UTC).isoformat(),
        "status": "research_scaffold",
        "humanMimicSource": str(human_source),
        "returnOptimizedSource": str(return_source) if return_source else None,
        "humanMimicTopRule": human_candidate,
        "returnOptimizedTopRule": return_candidate,
        "topRule": human_candidate,
        "warnings": warnings,
    }


def pine_expression(feature: str) -> tuple[str, list[str]]:
    comments: list[str] = []
    mapping = {
        "feature_close": ("close", []),
        "feature_close_above_ema25": ("close > ta.ema(close, 25)", []),
        "feature_close_above_sma100": ("close > ta.sma(close, 100)", []),
        "feature_distance_to_ema25_pct": (
            "((close - ta.ema(close, 25)) / ta.ema(close, 25)) * 100",
            [],
        ),
        "feature_distance_to_sma100_pct": (
            "((close - ta.sma(close, 100)) / ta.sma(close, 100)) * 100",
            [],
        ),
        "feature_recent_5_return_pct": ("((close - close[5]) / close[5]) * 100", []),
        "feature_recent_10_return_pct": ("((close - close[10]) / close[10]) * 100", []),
        "feature_recent_20_return_pct": ("((close - close[20]) / close[20]) * 100", []),
        "feature_recent_20_high": ("ta.highest(high, 20)", []),
        "feature_recent_20_low": ("ta.lowest(low, 20)", []),
        "feature_close_rank_recent_20": (
            "((close - ta.lowest(low, 20)) / math.max(ta.highest(high, 20) - ta.lowest(low, 20), syminfo.mintick))",
            [],
        ),
    }
    if feature in mapping:
        return mapping[feature]
    comments.append(f"TODO: map EdgeLord export feature `{feature}` to a Pine expression.")
    return ("na", comments)


def numeric_literal(value: Any) -> str:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "na"
    return f"{numeric:.10g}"


def comparison_operator(direction: Any) -> str:
    return ">=" if direction == ">=" else "<="


def rule_comment(prefix: str, candidate: dict[str, Any] | None) -> list[str]:
    if not candidate:
        return [f"// {prefix}: no candidate available"]
    feature = str(candidate.get("feature", ""))
    direction = comparison_operator(candidate.get("direction"))
    threshold = numeric_literal(candidate.get("threshold"))
    details: list[str] = []
    if "precision" in candidate:
        details.append(f"precision={float(candidate.get('precision', 0)):.4f}")
    if "recall" in candidate:
        details.append(f"recall={float(candidate.get('recall', 0)):.4f}")
    if "lift" in candidate:
        details.append(f"lift={float(candidate.get('lift', 0)):.4f}")
    if "avg_return_pct" in candidate:
        details.append(f"avg_return={float(candidate.get('avg_return_pct', 0)):.4f}%")
    if "lift_vs_baseline_pct" in candidate:
        details.append(f"lift_vs_baseline={float(candidate.get('lift_vs_baseline_pct', 0)):.4f}%")
    suffix = f" ({', '.join(details)})" if details else ""
    return [f"// {prefix}: {feature} {direction} {threshold}{suffix}"]


def pine_stub(human_candidate: dict[str, Any] | None, return_candidate: dict[str, Any] | None) -> str:
    lines = [
        "//@version=5",
        'strategy("EdgeLord SOXL/SOXS Candidate Scaffold", overlay=true, pyramiding=0)',
        "",
        "// Generated by EdgeLord research tooling.",
        "// Research scaffold only. Validate the rule, feature mapping, and symbol behavior before TradingView use.",
        "// This is not a live-trading strategy.",
        "",
    ]
    lines.extend(rule_comment("Human-mimic candidate", human_candidate))
    lines.extend(rule_comment("Return-optimized candidate", return_candidate))
    lines.append("")

    if not human_candidate:
        lines.extend([
            "// No human-mimic candidate rule is available yet.",
            "// Add replay-safe ENTRY and SKIP labels, then rerun `pnpm research:report`.",
            "candidateSignal = false",
        ])
    else:
        feature = str(human_candidate.get("feature", ""))
        direction = comparison_operator(human_candidate.get("direction"))
        threshold = numeric_literal(human_candidate.get("threshold"))
        expression, comments = pine_expression(feature)
        lines.extend(f"// {comment}" for comment in comments)
        lines.extend([
            f"candidateFeature = {expression}",
            f"candidateSignal = not na(candidateFeature) and candidateFeature {direction} {threshold}",
        ])

    lines.extend([
        "",
        'plotshape(candidateSignal, title="Candidate ENTRY", style=shape.triangleup, location=location.belowbar, size=size.tiny)',
        'if candidateSignal and strategy.position_size == 0',
        '    strategy.entry("Candidate Long", strategy.long)',
        "",
        "// Exits are intentionally not generated yet.",
        "// EdgeLord needs tested exit rules or explicit exported exit logic before this becomes a complete strategy.",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate EdgeLord strategy-rules JSON and a Pine Script scaffold.")
    parser.add_argument("--rules-json", required=True, type=Path, help="Path to candidate-rules.json")
    parser.add_argument("--return-rules-json", type=Path, help="Optional path to return-rules.json")
    parser.add_argument("--rules-output", required=True, type=Path, help="Path to write strategy_rules.v1.json")
    parser.add_argument("--pine-output", required=True, type=Path, help="Path to write strategy_soxl_soxs.pine")
    args = parser.parse_args()

    candidate_rules = read_rules(args.rules_json)
    human_candidate = top_candidate(candidate_rules)
    return_candidate = top_candidate(read_rules(args.return_rules_json)) if args.return_rules_json else None

    args.rules_output.parent.mkdir(parents=True, exist_ok=True)
    args.rules_output.write_text(
        f"{json.dumps(strategy_rules_payload(args.rules_json, human_candidate, args.return_rules_json, return_candidate), indent=2)}\n"
    )

    args.pine_output.parent.mkdir(parents=True, exist_ok=True)
    args.pine_output.write_text(pine_stub(human_candidate, return_candidate))


if __name__ == "__main__":
    main()
